{
 "title": "AmbientCollector",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "geographic_location",
    "label": "Location",
    "query": {
     "query": "label_values(weather_current_temperature_degC{location=\"$geographic_location\"},location)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Current values", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Temperature",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "living room",
     "expr": "envsensor_temperature_degC{location=\"living room\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "legendFormat": "Living room",
     "measurement": "environment_sensor",
     "select": [
      [
       { "params": [ "Temperature" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Location::tag", "operator": "=", "value": "Living room" }
     ]
    },
    {
     "alias": "bathroom",
     "expr": "envsensor_temperature_degC{location=\"bathroom\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "legendFormat": "Bathroom",
     "measurement": "environment_sensor",
     "select": [
      [
       { "params": [ "Temperature" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Location::tag", "operator": "=", "value": "Bathroom" }
     ]
    },
    {
     "alias": "bedroom",
     "expr": "envsensor_temperature_degC{location=\"bedroom\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "legendFormat": "Bedroom",
     "measurement": "environment_sensor",
     "select": [
      [
       { "params": [ "Temperature" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Location::tag", "operator": "=", "value": "Bedroom" }
     ]
    }
   ]
  },
  {
   "title": "Temperature in $geographic_location",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "weather_current_temperature_degC{location=\"$geographic_location\"}",
     "legendFormat": "actual"
    },
    {
     "expr": "weather_current_temperatureApparent_degC{location=\"$geographic_location\"}",
     "legendFormat": "apparent"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "living room",
     "expr": "envsensor_humidity_percent{location=\"living room\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "legendFormat": "Living room",
     "measurement": "environment_sensor",
     "select": [
      [
       { "params": [ "Humidity" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Location::tag", "operator": "=", "value": "Living room" }
     ]
    },
    {
     "alias": "bathroom",
     "expr": "envsensor_humidity_percent{location=\"bathroom\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "legendFormat": "Bathroom",
     "measurement": "environment_sensor",
     "select": [
      [
       { "params": [ "Humidity" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Location::tag", "operator": "=", "value": "Bathroom" }
     ]
    },
    {
     "alias": "bedroom",
     "expr": "envsensor_humidity_percent{location=\"bedroom\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "legendFormat": "Bedroom",
     "measurement": "environment_sensor",
     "select": [
      [
       { "params": [ "Humidity" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Location::tag", "operator": "=", "value": "Bedroom" }
     ]
    }
   ]
  },
  {
   "title": "Humidity in $geographic_location",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "weather_current_humidity_percent{location=\"$geographic_location\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "legendFormat": "__auto",
     "measurement": "weather_report",
     "select": [
      [
       { "params": [ "Humidity" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Location::tag", "operator": "=~", "value": "/^$geographic_location$/" }
     ]
    }
   ]
  },
  {
   "title": "Wind speed in $geographic_location",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "velocityms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "weather_current_windSpeed_meters_per_second{location=\"$geographic_location\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "legendFormat": "__auto",
     "measurement": "weather_report",
     "select": [
      [
       { "params": [ "WindSpeed" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Location::tag", "operator": "=~", "value": "/^$geographic_location$/" }
     ]
    }
   ]
  },
  {
   "title": "Pressure in $geographic_location",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "weather_current_pressure_hPa{location=\"$geographic_location\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Overall health",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Living room",
     "expr": "delta(envsensor_temperature_degC{location=\"living room\"}[60m])",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "legendFormat": "__auto",
     "measurement": "environment_sensor",
     "query": "SELECT last(\"Temperature\") FROM \"environment_sensor\" WHERE (\"Location\"::tag = 'Living room') AND time > now() - 1m",
     "select": [
      [
       { "params": [ "Temperature" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Location::tag", "operator": "=", "value": "Living room" },
      { "condition": "AND", "key": "time", "operator": "=", "value": "time - 5m" }
     ]
    },
    {
     "alias": "Living room",
     "expr": "delta(envsensor_temperature_degC{location=\"bathroom\"}[60m])",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "legendFormat": "__auto",
     "measurement": "environment_sensor",
     "query": "SELECT last(\"Temperature\") FROM \"environment_sensor\" WHERE (\"Location\"::tag = 'Living room') AND time > now() - 1m",
     "select": [
      [
       { "params": [ "Temperature" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Location::tag", "operator": "=", "value": "Living room" },
      { "condition": "AND", "key": "time", "operator": "=", "value": "time - 5m" }
     ]
    },
    {
     "alias": "Living room",
     "expr": "delta(envsensor_temperature_degC{location=\"bedroom\"}[60m])",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "legendFormat": "__auto",
     "measurement": "environment_sensor",
     "query": "SELECT last(\"Temperature\") FROM \"environment_sensor\" WHERE (\"Location\"::tag = 'Living room') AND time > now() - 1m",
     "select": [
      [
       { "params": [ "Temperature" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Location::tag", "operator": "=", "value": "Living room" },
      { "condition": "AND", "key": "time", "operator": "=", "value": "time - 5m" }
     ]
    }
   ]
  },
  {
   "title": "Time series",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Temperature",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
     "targets": [
      {
       "alias": "living room",
       "expr": "envsensor_temperature_degC{location=\"living room\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "legendFormat": "Living room",
       "measurement": "environment_sensor",
       "select": [
        [
         { "params": [ "Temperature" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "Location::tag", "operator": "=", "value": "Living room" }
       ]
      },
      {
       "alias": "bathroom",
       "expr": "envsensor_temperature_degC{location=\"bathroom\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "legendFormat": "Bathroom",
       "measurement": "environment_sensor",
       "select": [
        [
         { "params": [ "Temperature" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "Location::tag", "operator": "=", "value": "Bathroom" }
       ]
      },
      {
       "alias": "bedroom",
       "expr": "envsensor_temperature_degC{location=\"bedroom\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "legendFormat": "Bedroom",
       "measurement": "environment_sensor",
       "select": [
        [
         { "params": [ "Temperature" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "Location::tag", "operator": "=", "value": "Bedroom" }
       ]
      },
      {
       "alias": "$geographic_location",
       "expr": "weather_current_temperature_degC{location=\"$geographic_location\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "legendFormat": "$geographic_location",
       "measurement": "weather_report",
       "select": [
        [
         { "params": [ "Temperature" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "Location::tag", "operator": "=~", "value": "/^$geographic_location$/" }
       ]
      }
     ]
    },
    {
     "title": "Humidity",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
     "targets": [
      {
       "alias": "living room",
       "expr": "envsensor_humidity_percent{location=\"living room\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "legendFormat": "Living room",
       "measurement": "environment_sensor",
       "select": [
        [
         { "params": [ "Humidity" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "Location::tag", "operator": "=", "value": "Living room" }
       ]
      },
      {
       "alias": "bathroom",
       "expr": "envsensor_humidity_percent{location=\"bathroom\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "legendFormat": "Bathroom",
       "measurement": "environment_sensor",
       "select": [
        [
         { "params": [ "Humidity" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "Location::tag", "operator": "=", "value": "Bathroom" }
       ]
      },
      {
       "alias": "bedroom",
       "expr": "envsensor_humidity_percent{location=\"bedroom\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "legendFormat": "Bedroom",
       "measurement": "environment_sensor",
       "select": [
        [
         { "params": [ "Humidity" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "Location::tag", "operator": "=", "value": "Bedroom" }
       ]
      },
      {
       "alias": "$geographic_location",
       "expr": "weather_current_humidity_percent{location=\"$geographic_location\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "legendFormat": "$geographic_location",
       "measurement": "weather_report",
       "select": [
        [
         { "params": [ "Humidity" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "Location::tag", "operator": "=~", "value": "/^$geographic_location$/" }
       ]
      }
     ]
    },
    {
     "title": "Rain intensity",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
     "targets": [
      {
       "expr": "weather_current_rainIntensity_mm_per_hour{location=~\"$geographic_location\"}",
       "legendFormat": "$geographic_location"
      }
     ]
    }
   ]
  },
  {
   "title": "Health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Version",
     "type": "stat",
     "gridPos": { "h": 2, "w": 5, "x": 0, "y": 44 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "cacheDurationSeconds": 300,
       "fields": [
        { "jsonPath": "$" }
       ],
       "method": "GET"
      }
     ]
    },
    {
     "title": "Living room sensor",
     "type": "stat",
     "gridPos": { "h": 2, "w": 5, "x": 5, "y": 44 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "Living room",
       "expr": "delta(envsensor_temperature_degC{location=\"living room\"}[60m])",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "legendFormat": "__auto",
       "measurement": "environment_sensor",
       "query": "SELECT last(\"Temperature\") FROM \"environment_sensor\" WHERE (\"Location\"::tag = 'Living room') AND time > now() - 1m",
       "select": [
        [
         { "params": [ "Temperature" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "Location::tag", "operator": "=", "value": "Living room" },
        { "condition": "AND", "key": "time", "operator": "=", "value": "time - 5m" }
       ]
      }
     ]
    },
    {
     "title": "Prometheus health",
     "type": "stat",
     "gridPos": { "h": 2, "w": 5, "x": 0, "y": 46 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "cacheDurationSeconds": 300,
       "fields": [
        { "jsonPath": "$" }
       ],
       "method": "GET"
      }
     ]
    },
    {
     "title": "Bathroom sensor",
     "type": "stat",
     "gridPos": { "h": 2, "w": 5, "x": 5, "y": 46 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "delta(envsensor_temperature_degC{location=\"bathroom\"}[60m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "EMQX health",
     "type": "stat",
     "gridPos": { "h": 2, "w": 5, "x": 0, "y": 48 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "cacheDurationSeconds": 300,
       "fields": [
        { "jsonPath": "$" }
       ],
       "method": "GET"
      },
      {
       "cacheDurationSeconds": 300,
       "fields": [
        { "jsonPath": "" }
       ],
       "method": "GET"
      }
     ]
    },
    {
     "title": "Bedroom sensor",
     "type": "stat",
     "gridPos": { "h": 2, "w": 5, "x": 5, "y": 48 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "delta(envsensor_temperature_degC{location=\"bedroom\"}[60m])",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}