name: Docker Image CI

on:
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
  
    - name: Fetch tags
      run: git fetch --tags

    - name: Get latest tag
      id: get_latest_tag
      run: echo "latest_tag=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag lucky-luke4411/ambientcollector:${{ env.latest_tag }}