name: Docker Image CI

on:
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Get latest tag
      id: get_latest_tag
      run: |
          git fetch --tags
          echo "latest_tag=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/ambientcollector:${{ env.latest_tag }}